version: "3"
services:
  nginx:
    image: nginx:1.18
    restart: unless-stopped
    ports:
      - "444:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./image:/srv/http/image
      - ./index.html:/srv/http/index.html
